version: '3.7'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - FLASK_APP=run.py
    command: bash -c "python -m flask run --host=0.0.0.0"
    volumes:
      - .:/opt/project
    ports:
      - "80:5000"